name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Generar JSON dinámico en la raíz
        run: |
          FECHA=$(date +"%Y-%m-%d %H:%M:%S")
          echo '{ "message": "Mensaje generado con GitHub Actions el '"$FECHA"'", "fecha": "'"$FECHA"'" }' > data.json
          ls -la

      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Subir TODO el contenido de la raíz

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


